# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickendiseasesapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_404adb52021645908fef863e54d45469 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6e8237bfdfe146d19b349e6d107af10b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickendiseasesapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_404adb52021645908fef863e54d45469 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_21df114c72094021bbe62b3451307600 }}
        images: 'chickendiseasesapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_404adb52021645908fef863e54d45469 }}/chicken:${{ github.sha }}'